POST http://azapprpc-appservice.azurewebsites.net/customer
Content-Type: application/json

{
    "FullName": "Renicius Pagotto Fostaini",
    "Address": "123 Main St",
    "Email": "renicius@test.com"
}

###

GET http://azapprpc-appservice.azurewebsites.net/customer/1